### ISSUE TITLE
Problem installing Plugin

### ISSUE THREAD

**Issue by poornerd** [Telerik-Verified-Plugins/AppleWatch#10]
I am using cordova cli 5.2.0 (after an npm update) - on OSX.

I get an error when installing the plugin:

```
$ cordova plugin add https://github.com/Telerik-Verified-Plugins/AppleWatch
Fetching plugin "https://github.com/Telerik-Verified-Plugins/AppleWatch" via git clone
Repository "https://github.com/Telerik-Verified-Plugins/AppleWatch" checked out to git ref "master".
Installing "cordova-plugin-applewatch" for ios
Failed to install 'cordova-plugin-applewatch':Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bp/myVitalityManager/applewatchtest/plugins/cordova-plugin-applewatch/src/ios/hooks/cordova/copy_watchkitfiles.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bp/myVitalityManager/applewatchtest/plugins/cordova-plugin-applewatch/src/ios/hooks/cordova/copy_watchkitfiles.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I have tried removing it with `cordova plugin remove cordova-plugin-applewatch`, and reinstalling after an `npm update` as well as a `npm install -g xcode` with no luck.

Can anyone help?

**Comment by EddyVerbruggen** [comment]
Hey Brian,

When you open a Terminal now and run `npm show xcode`, what does it say? Looks like it's still missing on your machine.

**Comment by poornerd** [comment]
hmm, I think it is there:

```
sfs-macbook-pro:applewatchtest bp$ npm show xcode

{ name: 'xcode',
  description: 'parser for xcodeproj/project.pbxproj files',
  'dist-tags': { latest: '0.8.0' },
  versions:
   [ '0.0.0',
     '0.1.0',
     '0.2.0',
     '0.2.1',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.3.3',
     '0.3.4',
     '0.3.5',
     '0.4.0',
     '0.4.1',
     '0.5.0',
     '0.5.1',
     '0.5.2',
     '0.5.3',
     '0.5.4',
     '0.5.5',
     '0.6.0',
     '0.6.1',
     '0.6.2',
     '0.6.3',
     '0.6.4',
     '0.6.5',
     '0.6.6',
     '0.6.7',
     '0.7.0',
     '0.7.2',
     '0.7.9',
     '0.8.0' ],
  maintainers:
   [ 'alunny <alunny@gmail.com>',
     'filmaj <maj.fil@gmail.com>',
     'shepheb <braden.shepherdson@gmail.com>',
     'anis <anis.kadri@gmail.com>' ],
  time:
   { modified: '2015-07-13T20:42:58.665Z',
     created: '2012-01-27T00:40:47.895Z',
     '0.0.0': '2012-01-27T00:40:49.688Z',
     '0.1.0': '2012-02-01T23:03:27.066Z',
     '0.2.0': '2012-02-02T22:27:46.871Z',
     '0.2.1': '2012-02-06T21:17:51.098Z',
     '0.3.0': '2012-05-24T04:56:59.037Z',
     '0.3.1': '2012-05-24T17:58:49.999Z',
     '0.3.2': '2012-05-27T06:16:12.801Z',
     '0.3.3': '2012-06-19T07:42:23.012Z',
     '0.3.4': '2012-06-19T21:53:26.867Z',
     '0.3.5': '2012-06-26T18:38:42.294Z',
     '0.4.0': '2012-08-06T22:57:21.198Z',
     '0.4.1': '2012-08-08T22:42:05.318Z',
     '0.5.0': '2012-10-15T03:00:56.908Z',
     '0.5.1': '2012-10-15T04:40:49.533Z',
     '0.5.2': '2012-10-18T20:58:39.788Z',
     '0.5.3': '2012-10-18T22:47:24.312Z',
     '0.5.4': '2012-10-18T22:57:45.654Z',
     '0.5.5': '2012-10-18T23:04:58.908Z',
     '0.6.0': '2012-10-31T22:12:03.802Z',
     '0.6.1': '2013-07-03T16:03:38.147Z',
     '0.6.2': '2013-11-01T19:28:41.877Z',
     '0.6.3': '2013-11-24T01:56:49.039Z',
     '0.6.4': '2014-01-10T19:36:36.934Z',
     '0.6.5': '2014-01-16T18:31:26.605Z',
     '0.6.6': '2014-01-16T22:38:00.222Z',
     '0.6.7': '2014-07-10T20:12:30.521Z',
     '0.7.0': '2015-05-29T15:12:42.520Z',
     '0.7.2': '2015-06-26T17:00:41.997Z',
     '0.7.9': '2015-07-09T18:50:39.494Z',
     '0.8.0': '2015-07-13T20:42:58.665Z' },
  author: 'Andrew Lunny <alunny@gmail.com>',
  repository: { url: 'git+https://github.com/alunny/node-xcode.git' },
  homepage: 'https://github.com/alunny/node-xcode#readme',
  contributors:
   [ 'Andrew Lunny (@alunny)',
     'Anis Kadri (@imhotep)',
     'Mike Reinstein (@mreinstein)',
     'Filip Maj (@filmaj)',
     'Brett Rudd (@goya)',
     'Bob Easterday (@bobeast)' ],
  bugs: { url: 'https://github.com/alunny/node-xcode/issues' },
  readmeFilename: 'README.md',
  users: { martinmose: true, pfremm: true },
  version: '0.8.0',
  main: 'index.js',
  engines: { node: '>=0.6.7' },
  dependencies:
   { pegjs: '0.6.2',
     'node-uuid': '1.3.3' },
  devDependencies: { nodeunit: '0.9.0' },
  scripts: { test: 'nodeunit test/parser test' },
  gitHead: '1b738a4babb665102bff8fad4c627ddfcbfb90b4',
  dist:
   { shasum: 'fe61edf9cb14f2bb07ca6cafdc864a4b4c1beed9',
     tarball: 'http://registry.npmjs.org/xcode/-/xcode-0.8.0.tgz' },
  directories: {} }

sfs-macbook-pro:applewatchtest bp$
```

**Comment by poornerd** [comment]
I wondered if it was a case sensitive thing, like maybe the code was looking for "Xcode", but then it probably would have said "Xcode" in the error

**Comment by EddyVerbruggen** [comment]
That looks fine. `xcode` is an npm module capable of manipulating Xcode's project files. The error you are seeing is a plugman hook trying to use that module.

So it must have been an npm configuration issue on your machine. But since `npm show xcode` spits out the correct bits it may have been resolved. If you start over again, do you have the same problem?

Just copy-paste these:

```
cordova create applewatchtest
cd applewatchtest
cordova platform add ios
.. you should do a few things here but let's ignore that for this test
cordova plugin add https://github.com/Telerik-Verified-Plugins/AppleWatch
```

**Comment by poornerd** [comment]
nope :-(

```
sfs-macbook-pro:test bp$ cordova create applewatchtest
Creating a new cordova project.
sfs-macbook-pro:test bp$ cd applewatchtest
sfs-macbook-pro:applewatchtest bp$ cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@3.9.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for ios
sfs-macbook-pro:applewatchtest bp$ cordova plugin add https://github.com/Telerik-Verified-Plugins/AppleWatch
Fetching plugin "https://github.com/Telerik-Verified-Plugins/AppleWatch" via git clone
Repository "https://github.com/Telerik-Verified-Plugins/AppleWatch" checked out to git ref "master".
Installing "cordova-plugin-applewatch" for ios
Failed to install 'cordova-plugin-applewatch':Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bp/myVitalityManager/test/applewatchtest/plugins/cordova-plugin-applewatch/src/ios/hooks/cordova/copy_watchkitfiles.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bp/myVitalityManager/test/applewatchtest/plugins/cordova-plugin-applewatch/src/ios/hooks/cordova/copy_watchkitfiles.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by poornerd** [comment]
Just checked - I have plugman 1.0 if that matters

**Comment by EddyVerbruggen** [comment]
Does `which node` do anything for you? If shoud be on your `echo $PATH`.

**Comment by poornerd** [comment]
yes, node is also in the path

```
$ which node
/usr/local/bin/node
```

**Comment by poornerd** [comment]
Not sure what the problem was, but since you thought it was a path problem I did:

```
npm init
npm install xcode --save
cordova plugin remove cordova-plugin-applewatch
cordova plugin add https://github.com/Telerik-Verified-Plugins/AppleWatch
```

Then it worked...

```
Fetching plugin "https://github.com/Telerik-Verified-Plugins/AppleWatch" via git clone
Repository "https://github.com/Telerik-Verified-Plugins/AppleWatch" checked out to git ref "master".
Installing "cordova-plugin-applewatch" for ios



                                 Configuring the
                             Cordova AppleWatch Plugin

                          `@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:
                         @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@`
                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:
                       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                      ;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@
                      @@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@@@@@  @@@@@
                      @@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@  @@@@@
                      @@@@@@@@@@@@@@@@@@@#  @@@@@@@@@@@@@@@@@@  @@@@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@
                      @@@@@@@@@@@@@@@`   ,`    @@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@`          ,@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@          `@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@'          @@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@,          @@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@;          @@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@           @@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@            @@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@            @@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@          +@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@:         @@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@.  +#   @@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  @@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                      ;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:
                         @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@`
                          `@@@@@@@@@@@@@@@@@@@@@@@@@@@@@:

Added source file DetailInterfaceController.m to HelloCordova WatchKit Extension
Added source file OneColumnRowType.m to HelloCordova WatchKit Extension
Added source file OneColumnSelectableRowType.m to HelloCordova WatchKit Extension
Added source file ParentInterfaceController.m to HelloCordova WatchKit Extension
Added source file TwoColumnsRowType.m to HelloCordova WatchKit Extension
Added source file WatchKitHelper.m to HelloCordova WatchKit Extension
Added source file WatchKitUIHelper.m to HelloCordova WatchKit Extension
Added header file DetailInterfaceController.h to HelloCordova WatchKit Extension
Added header file OneColumnRowType.h to HelloCordova WatchKit Extension
Added header file OneColumnSelectableRowType.h to HelloCordova WatchKit Extension
Added header file ParentInterfaceController.h to HelloCordova WatchKit Extension
Added header file TwoColumnsRowType.h to HelloCordova WatchKit Extension
Added header file WatchKitHelper.h to HelloCordova WatchKit Extension
Added header file WatchKitUIHelper.h to HelloCordova WatchKit Extension
Added framework reference for libmmwormhole.a to target HelloCordova (1 of 2)
Added framework reference for libmmwormhole.a to target HelloCordova (2 of 2)
Copied Interface.storyboard to HelloCordova WatchKit App
Changed debug and release deployment targets of HelloCordova WatchKit App to 8.2
```

**Comment by EddyVerbruggen** [comment]
Good job, Brian!

**Comment by poornerd** [comment]
@EddyVerbruggen Thanks for your help!

**Comment by hgoebl** [comment]
I had the same problem. Seems like README.md is not correct. Installing npm module xcode globally doesn't work, has to be installed locally.

**Comment by poornerd** [comment]
@hgoebl oops - I forgot to tell you about this problem, too ;-)

**Comment by EddyVerbruggen** [comment]
@hgoebl @poornerd I think that slipped my mind - Happy to merge a PR so the doc can be improved.
