### ISSUE TITLE
Issue with plugin installation.

### ISSUE THREAD

**Issue by jd0048** [Telerik-Verified-Plugins/AppleWatch#40]
Hello

i am recently trying to implement apple watch app and try to install this plugin in my Cordova project but its failed to install plugin in my Cordova project.

`cordova plugin add https://github.com/Telerik-Verified-Plugins/AppleWatch`

got error:

`(node:1415) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin https://github.com/Telerik-Verified-Plugins/AppleWatch via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: git+https://github.com/Telerik-Verified-Plugins/AppleWatch.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jd/.npm/_logs/2018-01-31T10_23_28_432Z-debug.log
(node:1415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ghost** [comment]
Same problema here

**Comment by jacksonrdlc** [comment]
Same.

**Comment by enricodeleo** [comment]
It's due to the version of cordova we use. In fact a `package.json` is required for all plugins. There's a pull request pending that should solve this issue.

**Comment by swetha-thoomoju** [comment]
Added the package.json file using plugman, But i see a different error msg.

> Cannot find module 'xcode'

Failed to install 'cordova-plugin-applewatch': Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/AccessQA/wesko_repo/APP/wesko-lock-app/plugins/cordova-plugin-applewatch/src/ios/hooks/cordova/copy_watchkitfiles.js:1:75)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)


Cannot find module 'xcode'

My app have **phonegap version 8.2.2** and **ios is of 4.5.4.** We need to give support for apple watch just do not know where to start, though we are doing different experiments getting stuck at some point. 

Can anyone suggest me from where to start to create ios watch app.
